### ISSUE TITLE
Provide Getting Started Guide

### ISSUE THREAD

**Issue by thombergs** [fi3te/JenkinsHue#2]
Provide a guide that explains the steps to do when I want to get JenkinsHue up and running. Which Philips Hue products do I need and how do I set them and the application up?

**Comment by fi3te** [comment]
Done 😄

**Comment by thombergs** [comment]
How do I create a user when not using LDAP? This should be explained in the Getting Started Guide.

**Comment by thombergs** [comment]
Never mind, just found it in the guide :)
